services:
  raasel:
    build: .
    image: raasel:latest
    container_name: raasel-website
    restart: unless-stopped
    volumes:
      - ./downloads:/usr/share/nginx/html/downloads:ro
    networks:
      default:
        aliases:
          - raasel-nginx

networks:
  default:
    external: true
    name: rproxy_nginx_gh_app-network
