server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = /privacy {
    try_files /privacy/index.html =404;
  }

  location = /terms {
    try_files /terms/index.html =404;
  }

  location = /aup {
    try_files /aup/index.html =404;
  }

  location = /copyright {
    try_files /copyright/index.html =404;
  }

  location = /ar/privacy {
    try_files /ar/privacy/index.html =404;
  }

  location = /ar/terms {
    try_files /ar/terms/index.html =404;
  }

  location = /ar/aup {
    try_files /ar/aup/index.html =404;
  }

  location = /ar/copyright {
    try_files /ar/copyright/index.html =404;
  }

  location = /light/privacy {
    try_files /light/privacy/index.html =404;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}